package adapter

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"

	"github.com/dipxsy/hued/internal/domain"
	"github.com/dipxsy/hued/internal/files"
)

type SketchyBar struct {
	configPath string
	colorsPath string
}

func NewSketchyBar(configDir string) *SketchyBar {
	root := filepath.Join(configDir, "sketchybar")
	return &SketchyBar{
		configPath: filepath.Join(root, "sketchybarrc"),
		colorsPath: filepath.Join(root, "colors.sh"),
	}
}

func (sketchybar *SketchyBar) Name() string { return "sketchybar" }
func (sketchybar *SketchyBar) Detect() bool {
	_, err := os.Stat(sketchybar.configPath)
	return err == nil
}
func (sketchybar *SketchyBar) Plan(_ domain.Theme) Action {
	return Action{Adapter: sketchybar.Name(), Detail: sketchybar.colorsPath + " + live config reload"}
}
func (sketchybar *SketchyBar) Apply(theme domain.Theme) domain.Result {
	if err := files.WriteAtomic(sketchybar.colorsPath, []byte(renderSketchyBarColors(theme)), 0o644); err != nil {
		return failed(sketchybar.Name(), "write generated palette", err)
	}
	return applied(sketchybar.Name(), sketchybar.colorsPath+"; running bar reloads live")
}
func (sketchybar *SketchyBar) PostCommit() error {
	if exec.Command("/usr/bin/pgrep", "-x", "sketchybar").Run() != nil {
		return nil
	}
	executable := firstDesktopExecutable("/opt/homebrew/bin/sketchybar", "/usr/local/bin/sketchybar")
	if executable == "" {
		return fmt.Errorf("SketchyBar is running but its executable was not found; reinstall it or add it to PATH")
	}
	if output, err := exec.Command(executable, "--reload").CombinedOutput(); err != nil {
		return fmt.Errorf("reload SketchyBar config: %w: %s", err, strings.TrimSpace(string(output)))
	}
	return nil
}

func renderSketchyBarColors(theme domain.Theme) string {
	palette := theme.Palette.Resolved(theme.Appearance)
	return strings.Join([]string{
		"# Generated by `hued set`; edit the Hued theme manifest instead.",
		fmt.Sprintf("BG_BASE=\"0x%s\"", hexDigits(palette.PanelBG)),
		fmt.Sprintf("BG_SURFACE=\"0x%s\"", hexDigits(palette.Surface0)),
		fmt.Sprintf("ACTIVE_SPACE_BG=\"0x%s\"", hexDigits(palette.ActiveSpaceBG)),
		fmt.Sprintf("FG_PRIMARY=\"0x%s\"", hexDigits(palette.Text)),
		fmt.Sprintf("FG_SECONDARY=\"0x%s\"", hexDigits(palette.Subtext0)),
		fmt.Sprintf("FG_DIM=\"0x%s\"", hexDigits(palette.Overlay0)),
		fmt.Sprintf("ACCENT=\"0x%s\"", hexDigits(palette.Accent)),
		fmt.Sprintf("GREEN=\"0x%s\"", hexDigits(palette.Green)),
		fmt.Sprintf("YELLOW=\"0x%s\"", hexDigits(palette.Yellow)),
		fmt.Sprintf("RED=\"0x%s\"", hexDigits(palette.Red)),
		"",
	}, "\n")
}

type JankyBorders struct {
	configPath string
	scriptPath string
}

func NewJankyBorders(configDir string) *JankyBorders {
	root := filepath.Join(configDir, "aerospace")
	return &JankyBorders{
		configPath: filepath.Join(root, "aerospace.toml"),
		scriptPath: filepath.Join(root, "borders.sh"),
	}
}

func (borders *JankyBorders) Name() string { return "jankyborders" }
func (borders *JankyBorders) Detect() bool {
	_, err := os.Stat(borders.configPath)
	return err == nil && firstDesktopExecutable("/opt/homebrew/bin/borders", "/usr/local/bin/borders") != ""
}
func (borders *JankyBorders) Plan(_ domain.Theme) Action {
	return Action{Adapter: borders.Name(), Detail: borders.scriptPath + " + live IPC reconfiguration"}
}
func (borders *JankyBorders) Apply(theme domain.Theme) domain.Result {
	if err := files.WriteAtomic(borders.scriptPath, []byte(renderJankyBorders(theme)), 0o755); err != nil {
		return failed(borders.Name(), "write generated theme script", err)
	}
	return applied(borders.Name(), borders.scriptPath+"; running borders update live through IPC")
}
func (borders *JankyBorders) PostCommit() error {
	command := exec.Command(borders.scriptPath)
	if exec.Command("/usr/bin/pgrep", "-x", "borders").Run() == nil {
		if output, err := command.CombinedOutput(); err != nil {
			return fmt.Errorf("reconfigure running JankyBorders: %w: %s", err, strings.TrimSpace(string(output)))
		}
		return nil
	}
	command.Stdin = nil
	command.Stdout = nil
	command.Stderr = nil
	command.SysProcAttr = &syscall.SysProcAttr{Setsid: true}
	if err := command.Start(); err != nil {
		return fmt.Errorf("start themed JankyBorders: %w", err)
	}
	return command.Process.Release()
}

func renderJankyBorders(theme domain.Theme) string {
	palette := theme.Palette.Resolved(theme.Appearance)
	return strings.Join([]string{
		"#!/usr/bin/env bash",
		"# Generated by `hued set`; edit the Hued theme manifest instead.",
		`borders_bin="$(command -v borders 2>/dev/null || true)"`,
		`if [ -z "$borders_bin" ] && [ -x /opt/homebrew/bin/borders ]; then borders_bin=/opt/homebrew/bin/borders; fi`,
		`if [ -z "$borders_bin" ] && [ -x /usr/local/bin/borders ]; then borders_bin=/usr/local/bin/borders; fi`,
		`if [ -z "$borders_bin" ]; then echo "JankyBorders executable not found; install it and rerun hued set" >&2; exit 1; fi`,
		fmt.Sprintf(`exec "$borders_bin" active_color=0xff%s inactive_color=0xff%s width=5.0 blacklist="Simulator"`, hexDigits(palette.Accent), hexDigits(palette.Surface1)),
		"",
	}, "\n")
}

func firstDesktopExecutable(candidates ...string) string {
	for _, candidate := range candidates {
		if info, err := os.Stat(candidate); err == nil && !info.IsDir() && info.Mode()&0o111 != 0 {
			return candidate
		}
	}
	return ""
}

func hexDigits(color string) string {
	return strings.TrimPrefix(color, "#")
}
