package adapter

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/dipxsy/hued/internal/domain"
	"github.com/dipxsy/hued/internal/files"
)

type SketchyBar struct {
	configPath string
	colorsPath string
}

func NewSketchyBar(configDir string) *SketchyBar {
	root := filepath.Join(configDir, "sketchybar")
	return &SketchyBar{
		configPath: filepath.Join(root, "sketchybarrc"),
		colorsPath: filepath.Join(root, "colors.sh"),
	}
}

func (sketchybar *SketchyBar) Name() string { return "sketchybar" }
func (sketchybar *SketchyBar) Detect() bool {
	_, err := os.Stat(sketchybar.configPath)
	return err == nil
}
func (sketchybar *SketchyBar) Plan(_ domain.Theme) Action {
	return Action{Adapter: sketchybar.Name(), Detail: sketchybar.colorsPath + " + live config reload"}
}
func (sketchybar *SketchyBar) Apply(theme domain.Theme) domain.Result {
	if err := files.WriteAtomic(sketchybar.colorsPath, []byte(renderSketchyBarColors(theme)), 0o644); err != nil {
		return failed(sketchybar.Name(), "write generated palette", err)
	}
	return applied(sketchybar.Name(), sketchybar.colorsPath+"; running bar reloads live")
}
func (sketchybar *SketchyBar) PostCommit() error {
	if exec.Command("/usr/bin/pgrep", "-x", "sketchybar").Run() != nil {
		return nil
	}
	executable := firstDesktopExecutable("/opt/homebrew/bin/sketchybar", "/usr/local/bin/sketchybar")
	if executable == "" {
		return fmt.Errorf("SketchyBar is running but its executable was not found; reinstall it or add it to PATH")
	}
	if output, err := exec.Command(executable, "--reload").CombinedOutput(); err != nil {
		return fmt.Errorf("reload SketchyBar config: %w: %s", err, strings.TrimSpace(string(output)))
	}
	return nil
}

func renderSketchyBarColors(theme domain.Theme) string {
	palette := theme.Palette.Resolved(theme.Appearance)
	return strings.Join([]string{
		"# Generated by `hued set`; edit the Hued theme manifest instead.",
		fmt.Sprintf("BG_BASE=\"0x%s\"", hexDigits(palette.PanelBG)),
		fmt.Sprintf("BG_SURFACE=\"0x%s\"", hexDigits(palette.Surface0)),
		fmt.Sprintf("ACTIVE_SPACE_BG=\"0x%s\"", hexDigits(palette.ActiveSpaceBG)),
		fmt.Sprintf("FG_PRIMARY=\"0x%s\"", hexDigits(palette.Text)),
		fmt.Sprintf("FG_SECONDARY=\"0x%s\"", hexDigits(palette.Subtext0)),
		fmt.Sprintf("FG_DIM=\"0x%s\"", hexDigits(palette.Overlay0)),
		fmt.Sprintf("ACCENT=\"0x%s\"", hexDigits(palette.Accent)),
		fmt.Sprintf("GREEN=\"0x%s\"", hexDigits(palette.Green)),
		fmt.Sprintf("YELLOW=\"0x%s\"", hexDigits(palette.Yellow)),
		fmt.Sprintf("RED=\"0x%s\"", hexDigits(palette.Red)),
		"",
	}, "\n")
}

func firstDesktopExecutable(candidates ...string) string {
	for _, candidate := range candidates {
		if info, err := os.Stat(candidate); err == nil && !info.IsDir() && info.Mode()&0o111 != 0 {
			return candidate
		}
	}
	return ""
}

func hexDigits(color string) string {
	return strings.TrimPrefix(color, "#")
}
