package adapter

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/dipxsy/hued/internal/domain"
	"github.com/dipxsy/hued/internal/files"
)

type Ghostty struct {
	home      string
	configDir string
	stateDir  string
}

func NewGhostty(home, configDir, stateDir string) *Ghostty {
	return &Ghostty{home: home, configDir: configDir, stateDir: stateDir}
}

func (ghostty *Ghostty) Name() string { return "ghostty" }

func (ghostty *Ghostty) Detect() bool {
	for _, path := range []string{
		filepath.Join(ghostty.configDir, "ghostty", "config.ghostty"),
		filepath.Join(ghostty.configDir, "ghostty", "config"),
		filepath.Join(ghostty.home, "Library", "Application Support", "com.mitchellh.ghostty", "config.ghostty"),
		filepath.Join(ghostty.home, "Library", "Application Support", "com.mitchellh.ghostty", "config"),
		"/Applications/Ghostty.app",
	} {
		if _, err := os.Stat(path); err == nil {
			return true
		}
	}
	return false
}

func (ghostty *Ghostty) Plan(_ domain.Theme) Action {
	return Action{
		Adapter: ghostty.Name(),
		Detail:  filepath.Join(ghostty.configDir, "ghostty", "themes", "herdr-global") + " + delayed live SIGUSR1 reload",
	}
}

func (ghostty *Ghostty) Apply(theme domain.Theme) domain.Result {
	// Keep the existing path: both Ghostty config locations already converge on it,
	// and changing that path was part of the previously unreliable reload behavior.
	themePath := filepath.Join(ghostty.configDir, "ghostty", "themes", "herdr-global")
	if err := files.WriteAtomic(themePath, []byte(renderGhostty(theme)), 0o644); err != nil {
		return domain.Result{Adapter: ghostty.Name(), Status: domain.ResultFailed, Detail: err.Error()}
	}

	xdgConfig := firstExisting(
		filepath.Join(ghostty.configDir, "ghostty", "config.ghostty"),
		filepath.Join(ghostty.configDir, "ghostty", "config"),
	)
	if xdgConfig != "" {
		if err := updateTextSetting(xdgConfig, "background", ghosttyBackground(theme)); err != nil {
			return domain.Result{Adapter: ghostty.Name(), Status: domain.ResultFailed, Detail: err.Error()}
		}
	}

	macConfig := firstExisting(
		filepath.Join(ghostty.home, "Library", "Application Support", "com.mitchellh.ghostty", "config.ghostty"),
		filepath.Join(ghostty.home, "Library", "Application Support", "com.mitchellh.ghostty", "config"),
	)
	if macConfig != "" {
		if err := updateTextSetting(macConfig, "theme", themePath); err != nil {
			return domain.Result{Adapter: ghostty.Name(), Status: domain.ResultFailed, Detail: err.Error()}
		}
	}
	return domain.Result{Adapter: ghostty.Name(), Status: domain.ResultApplied, Detail: themePath}
}

func (ghostty *Ghostty) PostCommit() error {
	if exec.Command("/usr/bin/pgrep", "-x", "ghostty").Run() != nil {
		return nil
	}
	executable, err := os.Executable()
	if err != nil {
		return fmt.Errorf("resolve Hued executable for delayed Ghostty reload: %w", err)
	}
	logPath := filepath.Join(ghostty.stateDir, "ghostty-reload.log")
	command := exec.Command(executable, "internal", "ghostty-reload", "--log", logPath)
	command.Stdin = nil
	command.Stdout = nil
	command.Stderr = nil
	command.SysProcAttr = &syscall.SysProcAttr{Setsid: true}
	if err := command.Start(); err != nil {
		return fmt.Errorf("schedule delayed Ghostty reload: %w", err)
	}
	return command.Process.Release()
}

func RunGhosttyReload(logPath string) error {
	time.Sleep(500 * time.Millisecond)
	command := exec.Command("/usr/bin/killall", "-31", "ghostty")
	err := command.Run()
	exitCode := 0
	if err != nil {
		var exitError *exec.ExitError
		if errors.As(err, &exitError) {
			exitCode = exitError.ExitCode()
		} else {
			exitCode = 1
		}
	}
	content := []byte("command=/usr/bin/killall -31 ghostty\nexit_status=" + strconv.Itoa(exitCode) + "\n")
	if writeErr := files.WriteAtomic(logPath, content, 0o644); writeErr != nil {
		return writeErr
	}
	return err
}

func renderGhostty(theme domain.Theme) string {
	p := theme.Palette.Resolved(theme.Appearance)
	ansi := []string{
		p.ActiveSpaceBG, p.Red, p.Green, p.Yellow, p.Blue, p.Mauve, p.Teal, p.Text,
		p.Surface0, p.Red, p.Green, p.Yellow, p.Blue, p.Mauve, p.Teal, p.Subtext0,
	}
	lines := []string{
		"# Generated by `hued set`; edit the Hued theme manifest instead.",
		"foreground = " + p.Text,
		"background = " + ghosttyBackground(theme),
		"cursor-color = " + p.Text,
		"cursor-text = " + p.PanelBG,
		"selection-foreground = " + p.Text,
		"selection-background = " + p.Surface1,
	}
	for index, value := range ansi {
		lines = append(lines, fmt.Sprintf("palette = %d=%s", index, value))
	}
	return strings.Join(lines, "\n") + "\n"
}

func ghosttyBackground(theme domain.Theme) string {
	if theme.Targets.GhosttyBackground != nil && *theme.Targets.GhosttyBackground != "" {
		return *theme.Targets.GhosttyBackground
	}
	return theme.Palette.Resolved(theme.Appearance).PanelBG
}

func updateTextSetting(path, key, value string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	mode := os.FileMode(0o644)
	if info, statErr := os.Stat(path); statErr == nil {
		mode = info.Mode().Perm()
	}
	return files.WriteAtomic(path, []byte(replaceSetting(string(content), key, value)), mode)
}

func firstExisting(paths ...string) string {
	for _, path := range paths {
		if _, err := os.Stat(path); err == nil {
			return path
		}
	}
	return ""
}
