package adapter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dipxsy/hued/internal/domain"
	"github.com/dipxsy/hued/internal/files"
)

type Neovim struct {
	configDir string
}

func NewNeovim(configDir string) *Neovim { return &Neovim{configDir: configDir} }
func (neovim *Neovim) Name() string      { return "neovim" }
func (neovim *Neovim) Detect() bool {
	_, err := os.Stat(filepath.Join(neovim.configDir, "nvim"))
	return err == nil
}
func (neovim *Neovim) Plan(_ domain.Theme) Action {
	return Action{Adapter: neovim.Name(), Detail: filepath.Join(neovim.configDir, "nvim", "lua", "herdr-sync.lua") + " + fs watcher reload"}
}
func (neovim *Neovim) Apply(theme domain.Theme) domain.Result {
	path := filepath.Join(neovim.configDir, "nvim", "lua", "herdr-sync.lua")
	if err := files.WriteAtomic(path, []byte(renderNeovim(theme)), 0o644); err != nil {
		return failed(neovim.Name(), "write generated highlights", err)
	}
	return applied(neovim.Name(), path+"; running configured sessions reload live")
}

func renderNeovim(theme domain.Theme) string {
	p := theme.Palette.Resolved(theme.Appearance)
	type highlight struct {
		name   string
		fg     string
		bg     string
		italic bool
	}
	groups := []highlight{
		{"Normal", p.Text, p.PanelBG, false}, {"NormalFloat", p.Text, p.PanelBG, false},
		{"CursorLine", "", p.Surface0, false}, {"LineNr", p.Overlay0, "", false},
		{"CursorLineNr", p.Overlay1, "", false}, {"Visual", "", p.Surface1, false},
		{"Search", p.Text, p.Surface1, false}, {"IncSearch", p.SurfaceDim, p.Accent, false},
		{"StatusLine", p.Text, p.ActiveSpaceBG, false}, {"StatusLineNC", p.Overlay0, p.SurfaceDim, false},
		{"WinSeparator", p.Separator, "", false}, {"Pmenu", p.Text, p.Surface0, false},
		{"PmenuSel", p.Text, p.Surface1, false}, {"Comment", p.Overlay0, "", true},
		{"String", p.Green, "", false}, {"Number", p.Peach, "", false},
		{"Function", p.Blue, "", false}, {"Identifier", p.Blue, "", false},
		{"Keyword", p.Mauve, "", false}, {"Type", p.Teal, "", false},
		{"Operator", p.Teal, "", false}, {"DiagnosticError", p.Red, "", false},
		{"DiagnosticWarn", p.Yellow, "", false}, {"DiagnosticInfo", p.Blue, "", false},
		{"DiagnosticHint", p.Teal, "", false}, {"DiffAdd", p.Green, p.SurfaceDim, false},
		{"DiffChange", p.Yellow, p.SurfaceDim, false}, {"DiffDelete", p.Red, p.SurfaceDim, false},
	}
	lines := []string{"-- Generated by `hued set`; edit the Hued theme manifest instead.", `vim.g.colors_name = "hued"`, "", "local h = vim.api.nvim_set_hl"}
	for _, group := range groups {
		attributes := make([]string, 0, 3)
		if group.fg != "" {
			attributes = append(attributes, fmt.Sprintf(`fg = %q`, group.fg))
		}
		if group.bg != "" {
			attributes = append(attributes, fmt.Sprintf(`bg = %q`, group.bg))
		}
		if group.italic {
			attributes = append(attributes, "italic = true")
		}
		lines = append(lines, fmt.Sprintf(`h(0, %q, { %s })`, group.name, strings.Join(attributes, ", ")))
	}
	return strings.Join(lines, "\n") + "\n"
}
