package adapter

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dipxsy/hued/internal/domain"
	"github.com/dipxsy/hued/internal/files"
)

type Obsidian struct {
	registry string
}

type obsidianRegistry struct {
	Vaults map[string]struct {
		Path string `json:"path"`
	} `json:"vaults"`
}

func NewObsidian(home string) *Obsidian {
	return &Obsidian{registry: filepath.Join(home, "Library", "Application Support", "obsidian", "obsidian.json")}
}

func (obsidian *Obsidian) Name() string { return "obsidian" }
func (obsidian *Obsidian) Detect() bool { _, err := os.Stat(obsidian.registry); return err == nil }
func (obsidian *Obsidian) Plan(_ domain.Theme) Action {
	return Action{Adapter: obsidian.Name(), Detail: "update and enable hued.css in registered vaults; snippets reload live"}
}
func (obsidian *Obsidian) Apply(theme domain.Theme) domain.Result {
	vaults, err := obsidian.vaultPaths()
	if err != nil {
		return failed(obsidian.Name(), "discover vaults", err)
	}
	updated := 0
	for _, vault := range vaults {
		configDir := filepath.Join(vault, ".obsidian")
		if _, err := os.Stat(configDir); err != nil {
			continue
		}
		path := filepath.Join(configDir, "snippets", "hued.css")
		if err := files.WriteAtomic(path, []byte(renderObsidian(theme)), 0o644); err != nil {
			return failed(obsidian.Name(), "write vault snippet", err)
		}
		if err := enableObsidianSnippet(filepath.Join(configDir, "appearance.json")); err != nil {
			return failed(obsidian.Name(), "enable vault snippet", err)
		}
		updated++
	}
	if updated == 0 {
		return domain.Result{Adapter: obsidian.Name(), Status: domain.ResultUnsupported, Detail: "no accessible registered vaults"}
	}
	return applied(obsidian.Name(), fmt.Sprintf("updated %d registered vault(s); snippets reload live", updated))
}

func (obsidian *Obsidian) vaultPaths() ([]string, error) {
	content, err := os.ReadFile(obsidian.registry)
	if err != nil {
		return nil, err
	}
	var registry obsidianRegistry
	if err := json.Unmarshal(content, &registry); err != nil {
		return nil, err
	}
	paths := make([]string, 0, len(registry.Vaults))
	for _, vault := range registry.Vaults {
		if vault.Path != "" {
			paths = append(paths, vault.Path)
		}
	}
	sort.Strings(paths)
	return paths, nil
}

func enableObsidianSnippet(path string) error {
	object := make(map[string]json.RawMessage)
	if content, err := os.ReadFile(path); err == nil {
		decoder := json.NewDecoder(bytes.NewReader(content))
		if err := decoder.Decode(&object); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	var enabled []string
	if raw, ok := object["enabledCssSnippets"]; ok {
		if err := json.Unmarshal(raw, &enabled); err != nil {
			return err
		}
	}
	for _, name := range enabled {
		if name == "hued" {
			return nil
		}
	}
	enabled = append(enabled, "hued")
	sort.Strings(enabled)
	raw, err := json.Marshal(enabled)
	if err != nil {
		return err
	}
	object["enabledCssSnippets"] = raw
	content, err := json.MarshalIndent(object, "", "  ")
	if err != nil {
		return err
	}
	return files.WriteAtomic(path, append(content, '\n'), 0o644)
}

func renderObsidian(theme domain.Theme) string {
	p := theme.Palette.Resolved(theme.Appearance)
	values := map[string]string{
		"--background-primary": p.PanelBG, "--background-primary-alt": p.ActiveSpaceBG,
		"--background-secondary": p.Surface0, "--background-secondary-alt": p.Surface1,
		"--background-modifier-border": p.Separator, "--background-modifier-hover": p.Surface1,
		"--background-modifier-active-hover": p.Surface1, "--text-normal": p.Text,
		"--text-muted": p.Subtext0, "--text-faint": p.Overlay0, "--text-accent": p.Accent,
		"--text-accent-hover": p.Blue, "--interactive-accent": p.Accent,
		"--interactive-accent-hover": p.Blue, "--text-error": p.Red, "--text-warning": p.Yellow,
		"--color-red": p.Red, "--color-green": p.Green, "--color-yellow": p.Yellow,
		"--color-blue": p.Blue, "--color-purple": p.Mauve, "--color-cyan": p.Teal,
	}
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	lines := []string{"/* Generated by `hued set`; edit the Hued theme manifest instead. */", "body, body.theme-dark, body.theme-light {", "  color-scheme: " + string(theme.Appearance) + " !important;"}
	for _, key := range keys {
		lines = append(lines, "  "+key+": "+values[key]+" !important;")
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n") + "\n"
}
