package adapter

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/dipxsy/hued/internal/domain"
	"github.com/dipxsy/hued/internal/files"
)

type Spotify struct {
	configDir string
}

func NewSpotify(configDir string) *Spotify { return &Spotify{configDir: configDir} }
func (spotify *Spotify) Name() string      { return "spotify" }
func (spotify *Spotify) Detect() bool {
	_, commandErr := exec.LookPath("spicetify")
	_, appErr := os.Stat("/Applications/Spotify.app")
	_, configErr := os.Stat(filepath.Join(spotify.configDir, "spicetify", "config-xpui.ini"))
	return commandErr == nil && appErr == nil && configErr == nil
}
func (spotify *Spotify) Plan(_ domain.Theme) Action {
	return Action{Adapter: spotify.Name(), Detail: "update the active Spicetify theme's Hued color scheme and refresh Spotify live"}
}
func (spotify *Spotify) Apply(theme domain.Theme) domain.Result {
	binary, err := exec.LookPath("spicetify")
	if err != nil {
		return failed(spotify.Name(), "find Spicetify", err)
	}
	colorPathOutput, commandErr := exec.Command(binary, "path", "-s", "color").CombinedOutput()
	if commandErr != nil {
		return failed(spotify.Name(), "find the active Spicetify color file", fmt.Errorf("%v: %s", commandErr, colorPathOutput))
	}
	colorPath := strings.TrimSpace(string(colorPathOutput))
	if colorPath == "" {
		return failed(spotify.Name(), "find the active Spicetify color file", fmt.Errorf("Spicetify returned an empty path"))
	}
	content, err := os.ReadFile(colorPath)
	if err != nil {
		return failed(spotify.Name(), "read the active Spicetify color file", err)
	}
	updated := replaceINISection(string(content), "hued", renderSpotifyColorBody(theme))
	if err := files.WriteAtomic(colorPath, []byte(updated), fileMode(colorPath)); err != nil {
		return failed(spotify.Name(), "write the Hued Spicetify color scheme", err)
	}
	if output, commandErr := exec.Command(binary, "config", "color_scheme", "hued", "inject_css", "1", "replace_colors", "1").CombinedOutput(); commandErr != nil {
		return failed(spotify.Name(), "select the Hued Spicetify color scheme", fmt.Errorf("%v: %s", commandErr, output))
	}
	if exec.Command("/usr/bin/pgrep", "-x", "Spotify").Run() != nil {
		return applied(spotify.Name(), "color scheme installed; Spotify is not running and will use it on next launch")
	}
	if output, commandErr := exec.Command(binary, "-n", "refresh").CombinedOutput(); commandErr != nil {
		return failed(spotify.Name(), "refresh running Spotify", fmt.Errorf("%v: %s", commandErr, output))
	}
	return applied(spotify.Name(), "Spotify refreshed live through Spicetify")
}

func renderSpotifyColorBody(theme domain.Theme) string {
	p := theme.Palette.Resolved(theme.Appearance)
	values := []struct{ key, value string }{
		{"text", p.Text}, {"subtext", p.Subtext0}, {"main", p.PanelBG},
		{"main-elevated", p.Surface0}, {"highlight", p.Surface0}, {"highlight-elevated", p.Surface1},
		{"sidebar", p.ActiveSpaceBG}, {"player", p.ActiveSpaceBG}, {"card", p.Surface1},
		{"shadow", p.SurfaceDim}, {"selected-row", p.Text}, {"button", p.Accent},
		{"button-active", p.Blue}, {"button-disabled", p.Overlay0}, {"tab-active", p.Accent},
		{"notification", p.Surface1}, {"notification-error", p.Red}, {"misc", p.PanelBG},
	}
	lines := []string{"; Generated by `hued set`; edit the Hued theme manifest instead."}
	for _, value := range values {
		lines = append(lines, fmt.Sprintf("%-20s = %s", value.key, strings.TrimPrefix(value.value, "#")))
	}
	return strings.Join(lines, "\n") + "\n"
}

func replaceINISection(content, section, body string) string {
	lines := strings.Split(strings.TrimRight(content, "\n"), "\n")
	header := "[" + section + "]"
	start := -1
	end := len(lines)
	for index, line := range lines {
		trimmed := strings.TrimSpace(line)
		if start == -1 && strings.EqualFold(trimmed, header) {
			start = index
			continue
		}
		if start != -1 && strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
			end = index
			break
		}
	}
	replacement := append([]string{header}, strings.Split(strings.TrimRight(body, "\n"), "\n")...)
	if start == -1 {
		if len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) != "" {
			lines = append(lines, "")
		}
		lines = append(lines, replacement...)
		return strings.Join(lines, "\n") + "\n"
	}
	lines = append(lines[:start], append(replacement, lines[end:]...)...)
	return strings.Join(lines, "\n") + "\n"
}
