#!/usr/bin/env bash

CONFIG_DIR="${CONFIG_DIR:-$HOME/.config/sketchybar}"
FG_DIM="0x727169"
ACTIVE_SPACE_BG="0x2a2a37"
ACCENT="0xdcd7ba"

if [ -r "$CONFIG_DIR/colors.sh" ]; then
  # Generated by Hued from the active semantic palette.
  source "$CONFIG_DIR/colors.sh"
fi

app_icon() {
  case "$1" in
    "com.apple.Safari" | Safari) echo "" ;;
    Firefox | "org.mozilla.firefox") echo "" ;;
    Zen | "app.zen-browser.zen") echo "󰺕" ;;
    "com.google.Chrome" | "Google Chrome") echo "" ;;
    "com.brave.Browser" | Brave*) echo "" ;;
    "company.thebrowser.Browser" | Arc) echo "󰞍" ;;
    "com.apple.Terminal" | Terminal) echo "" ;;
    "com.googlecode.iterm2" | iTerm2) echo "" ;;
    Ghostty | "com.mitchellh.ghostty") echo "" ;;
    "net.kovidgoyal.kitty" | kitty) echo "" ;;
    Code | "com.microsoft.VSCode") echo "" ;;
    "com.apple.dt.Xcode" | Xcode) echo "" ;;
    Discord | "com.hnc.Discord" | Vesktop | "dev.vencord.vesktop") echo "" ;;
    "com.tinyspeck.slackmacgap" | Slack) echo "" ;;
    "us.zoom.xos" | zoom.us | Zoom) echo "" ;;
    "com.apple.FaceTime" | FaceTime) echo "" ;;
    "com.apple.iChat" | Messages) echo "" ;;
    "com.apple.mail" | Mail) echo "" ;;
    Spotify | "com.spotify.client") echo "" ;;
    "com.apple.Music" | Music) echo "" ;;
    "com.apple.finder" | Finder) echo "" ;;
    "com.apple.systempreferences" | "com.apple.SystemSettings" | \
      "System Preferences" | "System Settings") echo "" ;;
    "com.apple.ActivityMonitor" | Activity\ Monitor) echo "" ;;
    "com.apple.Preview" | Preview) echo "" ;;
    "com.apple.Photos" | Photos) echo "" ;;
    "com.apple.Calculator" | Calculator) echo "" ;;
    "com.apple.iCal" | Calendar) echo "" ;;
    "com.apple.Notes" | Notes) echo "" ;;
    "com.apple.Reminders" | Reminders) echo "" ;;
    "com.apple.Maps" | Maps) echo "" ;;
    "com.apple.TextEdit" | TextEdit) echo "" ;;
    "com.apple.Shortcuts" | Shortcuts) echo "" ;;
    "com.apple.Home" | Home) echo "" ;;
    "com.apple.Books" | Books) echo "" ;;
    "md.obsidian" | Obsidian) echo "" ;;
    "com.todoist.mac.Todoist" | Todoist) echo "" ;;
    "com.microsoft.Word" | Microsoft\ Word) echo "" ;;
    "com.microsoft.Excel" | Microsoft\ Excel) echo "" ;;
    "com.microsoft.Powerpoint" | Microsoft\ PowerPoint) echo "" ;;
    "com.docker.docker" | Docker) echo "" ;;
    "com.github.GitHubClient" | GitHub\ Desktop) echo "" ;;
    "ru.keepcoder.Telegram" | Telegram) echo "" ;;
    *) echo "" ;;
  esac
}

focused_workspace="${FOCUSED_WORKSPACE:-$(aerospace list-workspaces --focused)}"
workspace_data="$(aerospace list-workspaces --all \
  --format '%{workspace}|%{monitor-appkit-nsscreen-screens-id}')"

while IFS='|' read -r sid display; do
  [ -z "$sid" ] && continue

  bundle_ids="$(aerospace list-windows --workspace "$sid" \
    --format '%{app-bundle-id}' | sort -u)"
  icons=""

  while IFS= read -r bundle_id; do
    [ -z "$bundle_id" ] && continue
    [ -n "$icons" ] && icons="$icons "
    icons="$icons$(app_icon "$bundle_id")"
  done <<< "$bundle_ids"

  args=(
    associated_display="$display"
    label="$icons"
    label.drawing=on
  )

  if [ "$sid" = "$focused_workspace" ]; then
    args+=(
      icon.highlight=on
      icon.padding_right=0
      background.color=0xff${ACTIVE_SPACE_BG:2}
      background.border_width=1
      background.border_color=0x80${ACCENT:2}
    )
  else
    args+=(
      icon.highlight=off
      icon.padding_right=2
      background.color=0x00000000
      background.border_width=0
    )
  fi

  sketchybar --set "workspace.$sid" "${args[@]}"
done <<< "$workspace_data"
