#!/bin/sh

CONFIG_DIR="${CONFIG_DIR:-$HOME/.config/sketchybar}"
FG_DIM="0x727169"
ACCENT="0xdcd7ba"
GREEN="0x98bb6c"
YELLOW="0xe6c384"
RED="0xe46876"

if [ -r "$CONFIG_DIR/colors.sh" ]; then
  # Generated by Hued from the active semantic palette.
  . "$CONFIG_DIR/colors.sh"
fi

if [ "$SENDER" = "mouse.exited.global" ]; then
  sketchybar --set "$NAME" popup.drawing=off
  "$CONFIG_DIR/plugins/popup_dismiss.sh" stop "$NAME"
  exit 0
fi

WIFI="$("$CONFIG_DIR/plugins/wifi_ssid.sh" 2>/dev/null)"
if [ -z "$WIFI" ]; then
  WIFI="$(ipconfig getsummary en0 | awk -F ' SSID : ' '/ SSID : / {print $2}')"
fi
[ "$WIFI" = "<redacted>" ] && WIFI=""

if [ -n "$WIFI" ]; then
  RSSI="${SKETCHYBAR_WIFI_RSSI:-$(osascript -l JavaScript \
    -e 'ObjC.import("CoreWLAN"); const i=$.CWWiFiClient.sharedWiFiClient.interface; i ? i.rssiValue : -100' \
    2>/dev/null)}"

  case "$RSSI" in
    -[0-9]|-[1-4][0-9]) ICON="󰤨"; COLOR="0xff${GREEN#0x}" ;;
    -5[0-9]) ICON="󰤥"; COLOR="0xff${ACCENT#0x}" ;;
    -6[0-9]) ICON="󰤢"; COLOR="0xff${YELLOW#0x}" ;;
    *) ICON="󰤟"; COLOR="0xff${RED#0x}" ;;
  esac

  CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/sketchybar"
  NETWORK_TYPE_CACHE="$CACHE_DIR/wifi-network-type"
  if [ -n "$SKETCHYBAR_WIFI_NETWORK_TYPE" ]; then
    NETWORK_TYPE="$SKETCHYBAR_WIFI_NETWORK_TYPE"
  elif [ "$SENDER" = "wifi_change" ] || [ "$SENDER" = "system_woke" ] || \
       [ "$SENDER" = "forced" ] || [ ! -r "$NETWORK_TYPE_CACHE" ]; then
    NETWORK_TYPE="$(/usr/sbin/system_profiler SPAirPortDataType -json 2>/dev/null \
      | /usr/bin/jq -r '[.. | objects | select(has("spairport_signal_noise")) | .spairport_network_type][0] // "unknown"')"
    /bin/mkdir -p "$CACHE_DIR"
    printf '%s\n' "$NETWORK_TYPE" > "$NETWORK_TYPE_CACHE"
  else
    NETWORK_TYPE="$(/bin/cat "$NETWORK_TYPE_CACHE")"
  fi

  GATEWAY="${SKETCHYBAR_WIFI_GATEWAY:-$(/sbin/route -n get default 2>/dev/null \
    | awk '/gateway:/ {print $2; exit}')}"
  CLIENT_ADDRESS="${SKETCHYBAR_WIFI_CLIENT_ADDRESS:-$(networksetup -getinfo Wi-Fi 2>/dev/null \
    | awk -F': ' '/^IP address:/ {print $2; exit}')}"
  CLAT46_ACTIVE="${SKETCHYBAR_WIFI_CLAT46_ACTIVE:-$(ipconfig getsummary en0 2>/dev/null \
    | awk -F' : ' '/CLAT46Active/ {gsub(/[[:space:]]/, "", $2); print tolower($2); exit}')}"
  IPV6_HOTSPOT=false
  if [ "$CLAT46_ACTIVE" = "true" ]; then
    case "$CLIENT_ADDRESS:$GATEWAY" in
      192.0.0.[0-7]:192.0.0.[0-7]) IPV6_HOTSPOT=true ;;
    esac
  fi

  if [ "$NETWORK_TYPE" = "spairport_network_type_sharing" ] || \
     [ "$GATEWAY" = "172.20.10.1" ] || [ "$IPV6_HOTSPOT" = "true" ]; then
    # macOS Personal/Instant Hotspot: retain RSSI color with a distinct access-point glyph.
    ICON="󰀂"
  fi
  LABEL="$WIFI"
else
  # Keep Wi-Fi visible when disconnected or powered off.
  ICON="󰤮"
  COLOR="0x80${FG_DIM#0x}"
  LABEL="Disconnected"
fi

sketchybar --set "$NAME" icon="$ICON" icon.color="$COLOR" label="$LABEL"
